### ISSUE TITLE
Do we still need pillow on Windows?

### ISSUE THREAD

**Issue by pokey** [wolfmanstout/talon-gaze-ocr#20]
My understanding is that Talon Windows now has built-in support for OCR on beta

**Comment by wolfmanstout** [comment]
Correct, you do not need any pip installs if you are on Windows Beta and you enable `user.ocr_use_talon_backend = 1`. I need to update the readme. More background on this below (copy/pasted from Slack):

PSA for Windows users: if you sync your talon-gaze-ocr repo on Windows it’ll break because I switched from the unmaintained winrt package to winsdk. There are two ways to fix this. If you’re on Windows beta Talon you can use the native Talon OCR integration with setting “user.ocr_use_talon_backend = 1”, and you will no longer need any pip installs (same as Mac). I plan to make this the default once this doesn't break Talon public users (either because it supports OCR or it throws an error when I import the ocr package). If you are on Windows public (non-beta) Talon then you will need to run %APPDATA%\talon\.venv\Scripts\pip.bat install winsdk as described in the [readme](https://github.com/wolfmanstout/talon-gaze-ocr). Sorry for any disruption!

**Comment by wolfmanstout** [comment]
This is now documented in the readme, so I'm closing.
