### ISSUE TITLE
Consider different ways to say "scroll up/down" by default

### ISSUE THREAD

**Issue by nriley** [wolfmanstout/talon-gaze-ocr#3]
These conflict with standard commands in knausj:

https://github.com/knausj85/knausj_talon/blob/e2fc3096d022cd6f6cc24f0ee921d2a7e6479080/misc/standard.talon#L4

**Comment by wolfmanstout** [comment]
Hmm, I wish there were an easier mechanism for maintaining different commands without having to fork the .talon files. I have those commands renamed to "screen up/down" in my fork, and I've followed this naming convention since before knausj (and I think Talon) existed, so it won't be fun to relearn them now.

I guess I could theoretically make this a setting, and populate a list with one element depending on that setting. Not the most readable in the .talon script, though.

Another option is to simply remove these from talon-gaze-ocr, as they don't really have anything to do with OCR. They are nice commands, though, and leverage my direct gaze handler to work without taking over the mouse.
