### ISSUE TITLE
"Pick" in addition to "choose"?

### ISSUE THREAD

**Issue by nriley** [wolfmanstout/talon-gaze-ocr#6]
I'm guessing I am somewhat unique in this as it is used in the knausj help system, but I have a lot of trouble with getting conformer to recognize `choose`. I have been using `pick` instead for the past week or so with good success.

Would you consider `choose|pick`? There is an analog in knausj with `microphone pick <number>`.

I use `pick` a lot as my default "press return" word and for selecting from lists (https://github.com/nriley/knausj_talon/blob/nriley/misc/pick.talon; this is also proposed for knausj in https://github.com/knausj85/knausj_talon/pull/881). Since I never want to do anything other than pick one of the matches when the overlay is visible, I've not had any problems with it coexisting with gaze-ocr.

**Comment by wolfmanstout** [comment]
I'm hesitant to add more variants because this could cause conflicts for others. As you may have guessed, I chose `choose` to align with knausj. 

That said, you can easily work around this without maintaining a fork. Simply add the following file elsewhere in your user folder:
```
mode: user.gaze_ocr_disambiguation
-
pick <number_small>: user.choose_gaze_ocr_option(number_small)
```

This is simply copied from gaze_ocr_disambiguation.talon, with the desired modification. This won't remove the existing command, but it sounds like that's okay.

**Comment by nriley** [comment]
Sounds good.
